### ISSUE TITLE
Playground site broken

### ISSUE THREAD

**Issue by FourteenBrush** [stsewd/tree-sitter-comment#40]
Js error:
```js
Uncaught (in promise) RuntimeError: Aborted(CompileError: wasm validation error: at offset 185698: byte size mismatch in code section). Build with -sASSERTIONS for more info.
    abort https://stsewd.dev/tree-sitter-comment/js/tree-sitter.js:1
    TreeSitter https://stsewd.dev/tree-sitter-comment/js/tree-sitter.js:1
```

**Comment by stsewd** [comment]
Thanks for bringing this up! I'll take a look in a couple of day. Wonder if it has been broken for a while or just recently :thinking:

**Comment by stsewd** [comment]
So, playground works locally, but for some reason it doesn't work on GitHub pages... I'm just serving content as is from the docs directory, not sure what else to try :/

**Comment by FourteenBrush** [comment]
Maybe try deploying it in debug mode? worth a try :slightly_smiling_face:

**Comment by Rudxain** [comment]
On Firefox 137 for Debian (Mozilla source, not deb `main`), the console prints this:
```
wasm streaming compile failed: CompileError: wasm validation error: at offset 93186: function body length too big [tree-sitter.js:1:6317]
falling back to ArrayBuffer instantiation [tree-sitter.js:1:6357]
failed to asynchronously prepare wasm: CompileError: wasm validation error: at offset 93186: function body length too big [tree-sitter.js:1:5941]
Aborted(CompileError: wasm validation error: at offset 93186: function body length too big) [tree-sitter.js:1:4922]
Uncaught (in promise) RuntimeError: Aborted(CompileError: wasm validation error: at offset 93186: function body length too big). Build with -sASSERTIONS for more info.
    abort https://stsewd.dev/tree-sitter-comment/js/tree-sitter.js:1
    TreeSitter https://stsewd.dev/tree-sitter-comment/js/tree-sitter.js:1
[tree-sitter.js:1:5014]
```

**Comment by stsewd** [comment]
Hi, I just update the project to the latest version of tree-sitter, playground isn't broken for me anymore https://stsewd.dev/tree-sitter-comment/.

**Comment by stsewd** [comment]
@Rudxain my site doesn't include any CSP headers, you are probably using an extension or something that's blocking the content. The first warning is valid, though (but that shouldn't prevent the page from working)

**Comment by Rudxain** [comment]
I've now disabled:
- all extensions
- "HTTPS only" mode
- "Enhanced tracking protection"

And I get the same logs 😕

**Comment by Rudxain** [comment]
It seems some cache wasn't invalidated after disabling uBO (I reloaded several times to no avail). The site works after opening in a FF Private tab (doesn't reuse cache when the session starts), or when adding to "Trusted sites" before opening it as a normal tab.

Likely related to uBlockOrigin/uBlock-issues#235
